language: java

dist: xenial
jdk: openjdk8
stages:
- test
- upgrade_minor
- upgrade_major
jobs:
  include:
    stage: test
    before_install:
    - mysql -e 'CREATE DATABASE tiketux_package;'
    env:
      MYSQL_DATABASE: tiketux_package
      MYSQL_ROOT_PASSWORD: secret
      DB_HOST: 127.0.0.1
      DB_DATABASE: tiketux_package
      DB_USERNAME: root
      DB_PASSWORD: ''
      QUEUE_DRIVER: database
      COMPOSER_MEMORY_LIMIT: -1
    services:
    - mysql
    addons:
      apt:
        sources:
        - mysql-5.7-trusty
        packages:
        - mysql-server
    before_script:
    - shopt -s extglob
    - cp .env.example .env
    - mkdir report
    - mkdir storage/json
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
    - npm install
    - composer require tiketux/token
    - php artisan key:generate
    - php artisan config:cache
    - php artisan migrate
    - php artisan passport:install
    script:
    - php vendor/bin/phpunit --coverage-text --colors=never --testdox
    - npm run test
