language: php
dist: trusty
stages:
- test
- upgrade_minor
- upgrade_major
jobs:
  include:
    stage: test
    before_install:
    - mysql -e 'CREATE DATABASE tiketux_package;'
    env:
      global: 
        - MYSQL_DATABASE: tiketux_package
        - MYSQL_ROOT_PASSWORD: secret
        - DB_HOST: 127.0.0.1
        - DB_DATABASE: tiketux_package
        - DB_USERNAME: root
        - DB_PASSWORD: ''
        - QUEUE_DRIVER: database
      matrix:
        - secure: "JTCRBWZr2zi1TVDrj348lr1tFNgYS5y9FsyhrO378ClaDiMm7/SYdq1Vq70UPz0RUHuMcguuJzU4iAUms2DsUhFPdVr8po9sCrXD25fEWxQ2k0QdpVfnlmPDDsgjl0u4PoYyNs9VFeqoptV2JkJKg9/K5Ll3rsTGGaCiVQUP5srpN8Czko1PAwEo1th7YvA2JARyZixSkz3tXjn6pW0J0NB8yE33vgmiMH7/FUpQTcDM2wfgVFQPAK9RJXj3df4gGCbjJehksqcQwH6qKYQCzWLTyN1La/NugQgmfQGfPQfdfHXceLUs6INXwngg6rh85K6cKE3Vcg/nRV01ZvogyKutIA69UZC+uWSE2s6mGw5Vt7E8EBYa1mhK5ZZ2qBKIC9hC7JyRVLwctZTQDh/dcNw+ebycYPwtzrYhJ5WGzuSLiMGux7KFsN8Q+4FqtojGS3qNTzE4zML4BO31rXjJjJ88Qtqbc4e8UHJB5/hgYiUvfD+Wngj6hUksql9su4WrxeNlaJuRHT1dGyHO5F5mUkvnH6leh6xyw2+l3evCyRH1ZWM7RozRKzGFLaB8LxOpKrH5tUQ/mzbjIzz0JjRpqh2eu2xdywi5H+4PWhtdy/7/ApyUQeo8sJpnLt+aeUwyhz0dY3S+lW+yGSSlS584FNVQP52ifUc1gl6KndRvypA="
    services:
    - mysql
    addons:
      apt:
        sources:
        - mysql-5.7-trusty
        packages:
        - mysql-server
    before_script:
    - shopt -s extglob
    - cp .env.example .env
    - mkdir report
    - mkdir storage/json
    - composer config repositories.core vcs git@github.com:euclidian/token.git
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
    - composer require tiketux/token
    - php artisan key:generate
    - php artisan config:cache
    - php artisan migrate
    - php artisan passport:install
    script:
    - php vendor/bin/phpunit --coverage-text --colors=never
